voiceanswer - funcionando/config/routes.rb
Rails.application.routes.draw do
  resources :trilhas

  resources :turmas

  resources :professors

  devise_for :users

  root :to => "professors#index"
end

voiceanswer - funcionando/app/models/professor.rb
class Professor < ActiveRecord::Base
	mount_uploader :foto, PictureUploader
end

voiceanswer - funcionando/app/models/trilha.rb
class Trilha < ActiveRecord::Base
	belongs_to :turma
end

voiceanswer - funcionando/app/models/turma.rb
class Turma < ActiveRecord::Base
	has_many :trilhas
end

voiceanswer - funcionando/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

voiceanswer - funcionando/app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @professors = Professor.all
    respond_with(@professors)
  end

  def show
    respond_with(@professor)
  end

  def new
    @professor = Professor.new
    respond_with(@professor)
  end

  def edit
  end

  def create
    @professor = Professor.new(professor_params)
    @professor.save
    respond_with(@professor)
  end

  def update
    @professor.update(professor_params)
    respond_with(@professor)
  end

  def destroy
    @professor.destroy
    respond_with(@professor)
  end

  private
    def set_professor
      @professor = Professor.find(params[:id])
    end

    def professor_params
      params.require(:professor).permit(:nome, :matricula, :email, :senha, :foto)
    end
end

voiceanswer - funcionando/app/controllers/trilhas_controller.rb
class TrilhasController < ApplicationController
  before_action :set_trilha, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @trilhas = Trilha.all
    respond_with(@trilhas)
  end

  def show
    respond_with(@trilha)
  end

  def new
    @trilha = Trilha.new
    respond_with(@trilha)
  end

  def edit
  end

  def create
    @trilha = Trilha.new(trilha_params)
    @trilha.save
    respond_with(@trilha)
  end

  def update
    @trilha.update(trilha_params)
    respond_with(@trilha)
  end

  def destroy
    @trilha.destroy
    respond_with(@trilha)
  end

  private
    def set_trilha
      @trilha = Trilha.find(params[:id])
    end

    def trilha_params
      params.require(:trilha).permit(:nivel, :tagAssunto, :codigoTurma)
    end
end

voiceanswer - funcionando/app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  before_action :set_turma, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @turmas = Turma.all
    respond_with(@turmas)
  end

  def show
    respond_with(@turma)
  end

  def new
    @turma = Turma.new
    respond_with(@turma)
  end

  def edit
  end

  def create
    @turma = Turma.new(turma_params)
    @turma.save
    respond_with(@turma)
  end

  def update
    @turma.update(turma_params)
    respond_with(@turma)
  end

  def destroy
    @turma.destroy
    respond_with(@turma)
  end

  private
    def set_turma
      @turma = Turma.find(params[:id])
    end

    def turma_params
      params.require(:turma).permit(:nome, :codigo)
    end
end

voiceanswer - funcionando/app/helpers/professors_helper.rb
module ProfessorsHelper
end

voiceanswer - funcionando/app/helpers/trilhas_helper.rb
module TrilhasHelper
end

voiceanswer - funcionando/app/helpers/turmas_helper.rb
module TurmasHelper
end

voiceanswer - funcionando/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Voiceanswer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
<%= yield %>

</body>
</html>

voiceanswer - funcionando/app/views/professors/_form.html.erb
<!-- form_for(@professor) do |f| %>-->
<%= form_for(@professor, :html => { :multipart => true }) do |f| %>
  <% if @professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% @professor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :matricula %><br>
    <%= f.text_field :matricula %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :senha %><br>
    <%= f.text_field :senha %>
  </div>
  <div class="field">
    <%= f.label :foto %><br>
    <%= f.file_field :foto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

voiceanswer - funcionando/app/views/professors/edit.html.erb
<h1>Editar professor</h1>

<%= render 'form' %>

<%= link_to 'Ver completo', @professor %> |
<%= link_to 'Voltar', professors_path %>

voiceanswer - funcionando/app/views/professors/index.html.erb
<h1>Área do Professor!</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Matricula</th>
      <th>Email</th>
      <th>Foto</th>
    </tr>
  </thead>

  <tbody>
    <% @professors.each do |professor| %>
      <tr>
        <td><%= professor.nome %></td>
        <td><%= professor.matricula %></td>
        <td><%= professor.email %></td>
        <td><%= professor.foto %></td>
      <tr>
        <!--<td><%= link_to 'Show', professor %></td>-->
        <td><%= link_to 'Editar perfil', edit_professor_path(professor) %></td>
        <!--Acho que deveria ser excluir o perfil, a caixa de texto já está adaptada :) -->
        <td><%= link_to 'Destroy', professor, method: :delete, data: { confirm: 'Tem certeza que deseja excluir o seu perfil?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--Isso tem que apagar???-->
<%= link_to 'Configurar perfil', new_professor_path %>
<br/>
<%= link_to 'Lista de turmas', turmas_path %>
<br/>
<!--listar turmas sem linkar-->
<%= link_to 'Nova turma', new_turma_path %>
<br/>
<%= link_to 'Lista de trilhas', trilhas_path %>
<br/>
<!--listar trilhas sem linkar-->
<!--Dar link pra as trilhas-->
<%= link_to 'Nova trilha', new_trilha_path %>

voiceanswer - funcionando/app/views/professors/new.html.erb
<h1>Configurar professor</h1>

<%= render 'form' %>

<%= link_to 'Voltar', professors_path %>

voiceanswer - funcionando/app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @professor.nome %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @professor.matricula %>
</p>

<p>
  <strong>Email:</strong>
  <%= @professor.email %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @professor.senha %>
</p>

<p>
  <strong>Foto:</strong>
  <!--<%= @professor.foto %>-->
  <%= image_tag(@professor.foto_url, :width => 150) if @professor.foto.present? %>
</p>

<%= link_to 'Editar', edit_professor_path(@professor) %> |
<%= link_to 'Voltar', professors_path %>

voiceanswer - funcionando/app/views/trilhas/_form.html.erb
<%= form_for(@trilha) do |f| %>
  <% if @trilha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trilha.errors.count, "error") %> prohibited this trilha from being saved:</h2>

      <ul>
      <% @trilha.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nivel %><br>
    <%= f.text_field :nivel %>
  </div>
  <div class="field">
    <%= f.label :tagAssunto %><br>
    <%= f.text_field :tagAssunto %>
  </div>
  
  
  <div class="field">
    <%= f.label :codigoTurma %><br>
    <%= collection_select(:trilha, :codigoTurma, Turma.all, :codigo, :codigo) %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

voiceanswer - funcionando/app/views/trilhas/edit.html.erb
<h1>Editing trilha</h1>

<%= render 'form' %>

<%= link_to 'Show', @trilha %> |
<%= link_to 'Back', trilhas_path %>

voiceanswer - funcionando/app/views/trilhas/index.html.erb
<h1>Listing trilhas</h1>

<table>
  <thead>
    <tr>
      <th>Nivel</th>
      <th>Tagassunto</th>
      <th>Codigoturma</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trilhas.each do |trilha| %>
      <tr>
        <td><%= trilha.nivel %></td>
        <td><%= trilha.tagAssunto %></td>
        <td><%= trilha.codigoTurma %></td>
        <td><%= link_to 'Show', trilha %></td>
        <td><%= link_to 'Edit', edit_trilha_path(trilha) %></td>
        <td><%= link_to 'Destroy', trilha, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Trilha', new_trilha_path %>

<%= link_to 'Voltar', professors_path %>

voiceanswer - funcionando/app/views/trilhas/new.html.erb
<h1>Criar trilha</h1>

<%= render 'form' %>

<!--<%= link_to 'Back', trilhas_path %>-->
<%= link_to 'Voltar', professors_path %>

voiceanswer - funcionando/app/views/trilhas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nivel:</strong>
  <%= @trilha.nivel %>
</p>

<p>
  <strong>Tagassunto:</strong>
  <%= @trilha.tagAssunto %>
</p>

<p>
  <strong>Codigoturma:</strong>
  <%= @trilha.codigoTurma %>
</p>

<%= link_to 'Edit', edit_trilha_path(@trilha) %> |
<%= link_to 'Back', trilhas_path %>

voiceanswer - funcionando/app/views/turmas/_form.html.erb
<%= form_for(@turma) do |f| %>
  <% if @turma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@turma.errors.count, "error") %> prohibited this turma from being saved:</h2>

      <ul>
      <% @turma.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :codigo %><br>
    <%= f.text_field :codigo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

voiceanswer - funcionando/app/views/turmas/edit.html.erb
<h1>Editing turma</h1>

<%= render 'form' %>

<%= link_to 'Show', @turma %> |
<%= link_to 'Back', turmas_path %>

voiceanswer - funcionando/app/views/turmas/index.html.erb
<h1>Listing turmas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Codigo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turmas.each do |turma| %>
      <tr>
        <td><%= turma.nome %></td>
        <td><%= turma.codigo %></td>
        <!--<td><%= link_to 'Show', turma %></td>-->
        <td><%= link_to 'Edit', edit_turma_path(turma) %></td>
        <td><%= link_to 'Excluir', turma, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova turma', new_turma_path %>
<%= link_to 'Voltar', professors_path %>

voiceanswer - funcionando/app/views/turmas/new.html.erb
<h1>Criar turma</h1>

<%= render 'form' %>

<!--<%= link_to 'Back', turmas_path %>-->
<%= link_to 'Voltar', professors_path %>

voiceanswer - funcionando/app/views/turmas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @turma.nome %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @turma.codigo %>
</p>

<%= link_to 'Edit', edit_turma_path(@turma) %> |
<!--<%= link_to 'Back', turmas_path %>-->
<%= link_to 'Back', professors_path %>